# Generated by Django 6.0.2 on 2026-03-26 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("VIBE", "0015_directmessage_forwarded_from"),
    ]

    operations = [
        migrations.AddField(
            model_name="directmessage",
            name="replied_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="replies",
                to="VIBE.directmessage",
            ),
        ),
        migrations.AlterField(
            model_name="follow",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("accepted", "Accepted")],
                default="accepted",
                max_length=20,
            ),
        ),
    ]
