# Generated by Django 6.0.2 on 2026-03-26 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("VIBE", "0016_directmessage_replied_to_alter_follow_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="last_active",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
