# Generated by Django 6.0.2 on 2026-04-04 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("HAPPNIX", "0023_group_message_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="family_role",
            field=models.CharField(
                choices=[
                    ("member", "Member"),
                    ("parent", "Parent"),
                    ("child", "Child"),
                    ("normal_admin", "Normal admin"),
                ],
                default="member",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="tags_and_mentions_permission",
            field=models.CharField(
                choices=[
                    ("everyone", "Everyone"),
                    ("followers", "Followers only"),
                    ("no_one", "No one"),
                ],
                default="everyone",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="BlockedAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocked_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocked_by_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("owner", "target"), name="unique_blocked_account"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("owner", models.F("target")), _negated=True
                        ),
                        name="prevent_self_blocked_account",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RestrictedAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="restricted_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="restricted_by_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("owner", "target"), name="unique_restricted_account"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("owner", models.F("target")), _negated=True
                        ),
                        name="prevent_self_restricted_account",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SavedProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_by_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("owner", "target"), name="unique_saved_profile"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("owner", models.F("target")), _negated=True
                        ),
                        name="prevent_self_saved_profile",
                    ),
                ],
            },
        ),
    ]
