from django.urls import path
from . import messaging, views, signin_signup

urlpatterns = [
    path('', views.index_page, name='Landing page'),
    path('signin/', views.Signup_signin_page, name='Signup/Signin'),
    path('signin/forgot_password/', views.forgot_password, name='Forgot Password'),
    path('signup/details/', views.signup_details_page, name='Signup Details'),
    path('signup/profile/', views.signup_profile_page, name='Signup Profile Optional'),
    path('api/auth/mobile/send-otp', signin_signup.send_mobile_otp, name='send-mobile-otp'),
    path('api/auth/mobile/verify-otp', signin_signup.verify_mobile_otp, name='verify-mobile-otp'),
    path('api/auth/mobile/resend-otp', signin_signup.resend_mobile_otp, name='resend-mobile-otp'),
    path('api/auth/password/forgot', signin_signup.forgot_password_request, name='forgot-password-request'),
    path('api/auth/username/login', signin_signup.login_with_password, name='login-with-password'),
    path('api/signup/details', signin_signup.register_user_details, name='register-user-details'),
    path('api/signup/profile', signin_signup.complete_profile_setup, name='complete-profile-setup'),
    path('api/events/create', views.create_event_api, name='create-event-api'),
    path('api/events/<int:event_id>', views.delete_event_api, name='delete-event-api'),
    path('api/events/mine', views.my_events_api, name='my-events-api'),
    path('api/events/nearby', views.nearby_events_api, name='nearby-events-api'),
    path('api/events/live', views.live_events_api, name='live-events-api'),
    path('api/tickets', views.tickets_api, name='tickets-api'),
    path('api/tickets/book', views.book_ticket_api, name='book-ticket-api'),
    path('ticket/<int:ticket_id>/', views.view_ticket_page, name='view-ticket-page'),
    path('api/tickets/<int:ticket_id>/pay', views.pay_ticket_api, name='pay-ticket-api'),
    path('api/tickets/<int:ticket_id>/group', views.update_group_ticket_api, name='update-group-ticket-api'),
    path('api/tickets/<int:ticket_id>/cancel', views.cancel_ticket_api, name='cancel-ticket-api'),
    path('api/tickets/<int:ticket_id>/archive', views.archive_ticket_api, name='archive-ticket-api'),
    path('api/tickets/<int:ticket_id>/delete', views.delete_ticket_api, name='delete-ticket-api'),
    path('api/users/search', views.search_users_api, name='search-users-api'),
    path('api/users/follow', views.follow_user_api, name='follow-user-api'),
    path('api/users/<int:user_id>/profile', views.public_profile_api, name='public-profile-api'),
    path('api/profile/me', views.current_profile_api, name='current-profile-api'),
    path('api/profile/privacy', views.profile_privacy_api, name='profile-privacy-api'),
    path('api/profile/follow-requests', views.follow_requests_api, name='follow-requests-api'),
    path('api/notifications', views.notifications_api, name='notifications-api'),
    path('api/notifications/activity', views.log_activity_api, name='log-activity-api'),
    path('api/profile/<str:graph_type>', views.profile_follow_graph_api, name='profile-follow-graph-api'),
    path('api/messages/conversations', messaging.conversations_api, name='message-conversations-api'),
    path('api/messages/conversations/start', messaging.start_conversation_api, name='message-start-conversation-api'),
    path('api/messages/conversations/<int:conversation_id>/messages', messaging.conversation_messages_api, name='message-conversation-messages-api'),
    path('api/messages/conversations/<int:conversation_id>/read', messaging.mark_conversation_read_api, name='message-conversation-read-api'),
    path('api/messages/messages/<int:message_id>/edit', messaging.edit_message_api, name='message-edit-api'),
    path('api/messages/messages/<int:message_id>/forward', messaging.forward_message_api, name='message-forward-api'),
    path('api/messages/messages/<int:message_id>/delete', messaging.delete_message_for_me_api, name='message-delete-for-me-api'),
    path('api/messages/messages/<int:message_id>/unsend', messaging.unsend_message_api, name='message-unsend-api'),
    path('api/messages/conversations/<int:conversation_id>/clear', messaging.clear_conversation_api, name='api_clear_conversation'),
    path('api/messages/conversations/<int:conversation_id>/delete', messaging.delete_conversation_api, name='api_delete_conversation'),
    path('location/custom/', views.custom_location_page, name='custom-location'),
    path('party-loader-demo/', views.party_loader_demo_page, name='Party Loader Demo'),
    path('home/', views.Home_page, name='Home Page'),
    path('logout/', views.logout_view, name='Logout'),
    path('api/auth/aadhaar/send-otp', signin_signup.send_aadhaar_otp_api, name='send-aadhaar-otp'),
    path('api/auth/aadhaar/verify-otp', signin_signup.verify_aadhaar_otp_api, name='verify-aadhaar-otp'),
]

